name: Publish to Maven Local

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build the library
        run: ./gradlew build

      - name: Publish to Maven Local
        run: ./gradlew publishToMavenLocal

      - name: Verify artifact in Maven Local
        run: |
          echo "Listing Maven Local folder:"
          ls -R ~/.m2/repository/com/ruviapps/lazy/swipe || echo "Artifact not found!"